name: "Cleanup - Actions"
on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Retain days'
        required: true
        type: string
        default: 30
      minimum_runs:
        description: 'Minimum runs to keep for each workflow'
        required: true
        type: string
        default: 0
      delete_workflow_pattern:
        description: 'Name/filename of workflow. Default is all.'
        required: false
        type: string
      delete_workflow_by_state_pattern:
        description: 'Remove workflow by state: active, deleted, disabled_fork, disabled_inactivity, disabled_manually'
        required: true
        default: All
        type: choice
        options:
          - All
          - active
          - deleted
          - disabled_inactivity
          - disabled_manually

jobs:
  
  delete-runs:
    name: "Delete old workflow runs"
    runs-on: ubuntu-latest
    
    steps:
      - uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days }}
          keep_minimum_runs: ${{ github.event.inputs.minimum_runs }}
          delete_workflow_pattern: ${{ github.event.inputs.delete_workflow_pattern }}
          delete_workflow_by_state_pattern: ${{ github.event.inputs.delete_workflow_by_state_pattern }}
