name: Docker-Staging

on:
  pull_request:
  push:
    branches:
      - chains/coreum

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  IMAGE: big-dipper-ui

jobs:
  Build-and-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      - run: |-
          gcloud --quiet auth configure-docker
      - name: Build
        run: |-
          export TAG=`ruby -e 'puts File.read("package.json").match(/"version": "(?<semver>(0|[1-9][0-9]*).(0|[1-9][0-9]*).(0|[1-9][0-9]*))"/)[:semver]'`
          echo "tag=$TAG" >> $GITHUB_ENV
          docker build \
            --tag "gcr.io/$PROJECT_ID/$IMAGE:$TAG" \
            --tag "gcr.io/$PROJECT_ID/$IMAGE:latest" \
            --build-arg NEXT_PUBLIC_GRAPHQL_URL="http://hasura:8080/v1/graphql" \
            --build-arg NEXT_PUBLIC_GRAPHQL_WS="ws://hasura:8080/v1/graphql" \
            --build-arg NEXT_PUBLIC_URL="http://0.0.0.0" \
            --build-arg NEXT_PUBLIC_RPC_WEBSOCKET="ws://cored:9090/websocket" \
            --build-arg NEXT_PUBLIC_CHAIN_TYPE="testnet" \
            --build-arg NODE_ENV="production" \
            --build-arg PORT=3000 \
            --build-arg NEXT_PUBLIC_MATOMO_URL="https://analytics.bigdipper.live" \
            --build-arg NEXT_PUBLIC_MATOMO_SITE_ID=4 \
            .
      - name: Publish
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:${{ env.tag }}" && \
          docker push "gcr.io/$PROJECT_ID/$IMAGE:latest"
