name: "Release"
on:
  workflow_call:
defaults:
  run:
    shell: bash


jobs:
  release-docker-testnet:
    name: "BigDipper Docker image - Testnet"
    runs-on: ubuntu-latest
    if: ${{ ( github.ref_name == 'main' ) }}
    environment: testnet
    env:
      IMAGE_NAME: ${{ github.repository }}

    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set network name
        id: set-network
        run: |
          NETWORK_NAME=${GITHUB_REF##*/}
          echo ::set-output name=NETWORK_NAME::"$NETWORK_NAME"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
          version: latest

      - name: Install DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Configure Docker image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: registry.digitalocean.com/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.set-network.outputs.NETWORK_NAME }}-latest
            type=sha,format=long
          labels: |
            org.opencontainers.image.description="BigDipper block explorer for cheqd network"
            org.opencontainers.image.source="https://github.com/cheqd/big-dipper-2.0-cosmos"
            org.opencontainers.image.vendor="Cheqd Foundation Limited"
            org.opencontainers.image.created={{date 'dddd, MMMM Do YYYY, h:mm:ss a'}}
            org.opencontainers.image.documentation="https://product.cheqd.io/"

      - name: Build BigDipper image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NODE_ENV="production"
            NEXT_PUBLIC_GRAPHQL_URL=${{ secrets.NEXT_PUBLIC_GRAPHQL_URL }}
            NEXT_PUBLIC_GRAPHQL_WS=${{ secrets.NEXT_PUBLIC_GRAPHQL_WS }}
            NEXT_PUBLIC_RPC_WEBSOCKET=${{ secrets.NEXT_PUBLIC_RPC_WEBSOCKET }}
            NEXT_PUBLIC_CHAIN_TYPE=${{ secrets.NEXT_PUBLIC_CHAIN_TYPE }}

      - name: Push BigDipper image
        run: docker image push --all-tags registry.digitalocean.com/${{ env.IMAGE_NAME }}
